FROM golang:1.23.0-bookworm AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download && go mod verify

COPY . .

RUN go build -ldflags "-s -w" -o /server .

FROM gcr.io/distroless/base-debian12

COPY --from=build /server /server

ENTRYPOINT ["/server"]
