{
 "title": "Cluster CPU/Memory Usage",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "arm64_cluster_price",
    "query": "m6g.xlarge : 0.154,m6a.xlarge : 0.1728"
   },
   {
    "name": "amd64_cluster_price",
    "query": "m6g.xlarge : 0.154,m6a.xlarge : 0.1728"
   }
  ]
 },
 "panels": [
  {
   "title": "ARM64 Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(\n    sum(\n        irate(\n            nginx_ingress_controller_requests\n            {\n                ingress=~\"go-app\"\n            }[1m]\n            )\n        ) by (ingress), 0.001)",
     "legendFormat": "Traffic"
    }
   ]
  },
  {
   "title": "AMD64 Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(\n    sum(\n        irate(\n            nginx_ingress_controller_requests\n            {\n                ingress=~\"go-app\"\n            }[1m]\n            )\n        ) by (ingress), 0.001)",
     "legendFormat": "Traffic"
    }
   ]
  },
  {
   "title": "CPU Usage % of the Limit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        container_cpu_usage_seconds_total\n        {\n            container_label_io_kubernetes_pod_namespace=~\"staging\",\n            image!=\"\",\n            container_label_io_cri_containerd_kind=\"container\"\n        }[1m]\n        )\n    )\nby (\n    container_label_io_kubernetes_pod_name,\n    container_label_io_kubernetes_container_name\n    ) /\nsum(\n    container_spec_cpu_quota\n    {\n        container_label_io_kubernetes_pod_namespace=~\"staging\",\n        image!=\"\",\n        container_label_io_cri_containerd_kind=\"container\"\n    } /\n    container_spec_cpu_period\n    {\n        container_label_io_kubernetes_pod_namespace=~\"staging\",\n        image!=\"\",\n        container_label_io_cri_containerd_kind=\"container\"\n    }\n    )\nby (\n    container_label_io_kubernetes_pod_name,\n    container_label_io_kubernetes_container_name\n    )",
     "legendFormat": "{{ container_label_io_kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "CPU Usage % of the Limit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        container_cpu_usage_seconds_total\n        {\n            container_label_io_kubernetes_pod_namespace=~\"staging\",\n            image!=\"\",\n            container_label_io_cri_containerd_kind=\"container\"\n        }[1m]\n        )\n    )\nby (\n    container_label_io_kubernetes_pod_name,\n    container_label_io_kubernetes_container_name\n    ) /\nsum(\n    container_spec_cpu_quota\n    {\n        container_label_io_kubernetes_pod_namespace=~\"staging\",\n        image!=\"\",\n        container_label_io_cri_containerd_kind=\"container\"\n    } /\n    container_spec_cpu_period\n    {\n        container_label_io_kubernetes_pod_namespace=~\"staging\",\n        image!=\"\",\n        container_label_io_cri_containerd_kind=\"container\"\n    }\n    )\nby (\n    container_label_io_kubernetes_pod_name,\n    container_label_io_kubernetes_container_name\n    )",
     "legendFormat": "{{ container_label_io_kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Cost per Day",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (instance, ec2_instance_type) (up{job=\"ec2-node-exporter\"} * $arm64_cluster_price * 24)",
     "legendFormat": "{{ ec2_instance_type }}"
    },
    {
     "expr": "sum by (ec2_instance_type) (up{job=\"ec2-node-exporter\"} * $arm64_cluster_price * 24)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cost per Day",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (instance, ec2_instance_type) (up{job=\"ec2-node-exporter\"} * $amd64_cluster_price * 24)",
     "legendFormat": "{{ ec2_instance_type }}"
    },
    {
     "expr": "sum by (ec2_instance_type) (up{job=\"ec2-node-exporter\"} * $amd64_cluster_price * 24)",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}