// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewDevice struct {
	Mac      string `json:"mac"`
	Firmware string `json:"firmware"`
}

type Query struct {
}
