# Generated by Django 5.1 on 2024-09-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.UUIDField(primary_key=True, serialize=False)),
                ('obj_key', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
