source "https://rubygems.org"

gem "falcon"
gem "oj"
gem "pg"
gem "prometheus-client"
gem "rage-rb"

gem "rails"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false
