{
 "title": "CPU Usage",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage % of the Limit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        container_cpu_usage_seconds_total\n        {\n            container_label_io_kubernetes_pod_namespace=~\"staging\",\n            image!=\"\", \n            container_label_io_cri_containerd_kind=\"container\"\n        }[1m]\n        )\n    )\nby (\n    container_label_io_kubernetes_pod_name, \n    container_label_io_kubernetes_container_name\n    ) /\nsum(\n    container_spec_cpu_quota\n    {\n        container_label_io_kubernetes_pod_namespace=~\"staging\",\n        image!=\"\", \n        container_label_io_cri_containerd_kind=\"container\"\n    } /\n    container_spec_cpu_period\n    {\n        container_label_io_kubernetes_pod_namespace=~\"staging\",\n        image!=\"\", \n        container_label_io_cri_containerd_kind=\"container\"\n    }\n    ) \nby (\n    container_label_io_kubernetes_pod_name, \n    container_label_io_kubernetes_container_name\n    )",
     "legendFormat": "{{ container_label_io_kubernetes_container_name }}"
    }
   ]
  },
  {
   "title": "CPU Usage in Cores with Requests and Limits",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        container_cpu_usage_seconds_total\n        {\n            container_label_io_kubernetes_pod_namespace=~\"staging\",\n            container_label_io_kubernetes_container_name=~\"java-app|go-app\", \n            image!=\"\", \n            container_label_io_cri_containerd_kind=\"container\"\n            }[1m]\n        )\n    ) \nby (\n    container_label_io_kubernetes_pod_name, \n    container_label_io_kubernetes_container_name\n    )",
     "legendFormat": "{{ container_label_io_kubernetes_container_name }}"
    },
    {
     "expr": "avg(\n    kube_pod_container_resource_limits\n    {\n        exported_namespace=~\"staging\", \n        exported_container=~\"go-app|java-app\",\n        unit=\"core\"\n    })",
     "legendFormat": "Limit"
    },
    {
     "expr": "avg(\n    kube_pod_container_resource_requests\n    {\n        exported_namespace=~\"staging\", \n        exported_container=~\"go-app|java-app\",\n        unit=\"core\"\n    })",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(\n    container_cpu_cfs_throttled_seconds_total\n    {\n        container_label_io_kubernetes_pod_namespace=~\"staging\",\n        container_label_io_cri_containerd_kind=\"container\",\n        image!=\"\"\n    }[1m])",
     "legendFormat": "{{ container_label_io_kubernetes_container_name }}"
    }
   ]
  }
 ]
}