{
 "title": "250-nginx-vs-haproxy-vs-traefik",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "disk", "query": "sdb, nvme1n1" }
  ]
 },
 "panels": [
  {
   "title": "Latency (p90)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(tester_request_duration_seconds_bucket{status=~\"2.*\", container=\"nginx-client\"}[30s])) by (le, container))",
     "legendFormat": "Nginx"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(tester_request_duration_seconds_bucket{status=~\"2.*\", container=\"haproxy-client\"}[30s])) by (le, container))",
     "legendFormat": "HAProxy"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(tester_request_duration_seconds_bucket{status=~\"2.*\", container=\"traefik-client\"}[30s])) by (le, container))",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(tester_request_duration_seconds_count{status=~\"2.*\", job=\"benchmark/nginx-client\"}[30s]))",
     "legendFormat": "Nginx"
    },
    {
     "expr": "sum(rate(tester_request_duration_seconds_count{status=~\"2.*\", job=\"benchmark/haproxy-client\"}[30s]))",
     "legendFormat": "HAProxy"
    },
    {
     "expr": "sum(rate(tester_request_duration_seconds_count{status=~\"2.*\", job=\"benchmark/traefik-client\"}[30s]))",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "CPU Usage (proxy)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{instance=\"nginx.antonputra.pvt:9100\",mode=\"idle\"}[30s])) * 100)",
     "legendFormat": "Nginx"
    },
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{instance=\"haproxy.antonputra.pvt:9100\",mode=\"idle\"}[30s])) * 100)",
     "legendFormat": "HAProxy"
    },
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{instance=\"traefik.antonputra.pvt:9100\",mode=\"idle\"}[30s])) * 100)",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "CPU Usage (backend)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{instance=\"app-nginx-0.antonputra.pvt:9100\",mode=\"idle\"}[30s])) * 100)",
     "legendFormat": "app-0 (nginx)"
    },
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{instance=\"app-nginx-1.antonputra.pvt:9100\",mode=\"idle\"}[30s])) * 100)",
     "legendFormat": "app-1 (nginx)"
    },
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{instance=\"app-haproxy-0.antonputra.pvt:9100\",mode=\"idle\"}[30s])) * 100)",
     "legendFormat": "app-0 (haproxy)"
    },
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{instance=\"app-haproxy-1.antonputra.pvt:9100\",mode=\"idle\"}[30s])) * 100)",
     "legendFormat": "app-1 (haproxy)"
    },
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{instance=\"app-traefik-0.antonputra.pvt:9100\",mode=\"idle\"}[30s])) * 100)",
     "legendFormat": "app-0 (traefik)"
    },
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{instance=\"app-traefik-1.antonputra.pvt:9100\",mode=\"idle\"}[30s])) * 100)",
     "legendFormat": "app-1 (traefik)"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        tester_request_duration_seconds_count\n        {\n            container=~\"nginx-client\",\n            status!~\"[4-5].*\"\n        }[30s])) by (container) /\nsum(\n    rate(\n        tester_request_duration_seconds_count\n        {\n            container=~\"nginx-client\"\n        }[30s])) by (container)",
     "legendFormat": "Nginx"
    },
    {
     "expr": "sum(\n    rate(\n        tester_request_duration_seconds_count\n        {\n            container=~\"haproxy-client\",\n            status!~\"[4-5].*\"\n        }[30s])) by (container) /\nsum(\n    rate(\n        tester_request_duration_seconds_count\n        {\n            container=~\"haproxy-client\"\n        }[30s])) by (container)",
     "legendFormat": "HAProxy"
    },
    {
     "expr": "sum(\n    rate(\n        tester_request_duration_seconds_count\n        {\n            container=~\"traefik-client\",\n            status!~\"[4-5].*\"\n        }[30s])) by (container) /\nsum(\n    rate(\n        tester_request_duration_seconds_count\n        {\n            container=~\"traefik-client\"\n        }[30s])) by (container)",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "Network Traffic (transmit)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{instance=\"nginx.antonputra.pvt:9100\"}[30s])*8)",
     "legendFormat": "Nginx"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{instance=\"haproxy.antonputra.pvt:9100\"}[30s])*8)",
     "legendFormat": "HAProxy"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{instance=\"traefik.antonputra.pvt:9100\"}[30s])*8)",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"nginx.antonputra.pvt:9100\"} - node_memory_MemFree_bytes{instance=\"nginx.antonputra.pvt:9100\"}",
     "legendFormat": "Nginx"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"haproxy.antonputra.pvt:9100\"} - node_memory_MemFree_bytes{instance=\"haproxy.antonputra.pvt:9100\"}",
     "legendFormat": "HAProxy"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"traefik.antonputra.pvt:9100\"} - node_memory_MemFree_bytes{instance=\"traefik.antonputra.pvt:9100\"}",
     "legendFormat": "Traefik"
    }
   ]
  }
 ]
}