# frozen_string_literal: true

source 'https://rubygems.org'

gem 'connection_pool'
gem 'pg'
gem 'rake'
gem 'standalone_migrations', require: false

gem 'oj'
gem 'prometheus-client'
gem 'rack'
gem 'rage-iodine'
